### ISSUE TITLE
V1S Not Support

### ISSUE THREAD

**Issue by iqbalbals** [mitsuharu/react-native-sunmi-printer-library#34]
**Describe the bug**
 LOG  🚀 ~ testPrint ~ prepare: {"_h": 0, "_i": 3, "_j": {"_h": 0, "_i": 2, "_j": "prepare() is failed.Cannot read property 'connect' of null", "_k": null, "_o": 0}, "_k": null}
 WARN  This device is not supported. 
**To Reproduce**
 try {
    const prepare = SunmiPrinterLibrary.prepare();
    console.log("🚀 ~ testPrint ~ prepare:", prepare);
    const printText = SunmiPrinterLibrary.printText("Hello World");
    console.log("🚀 ~ testPrint ~ printText:", printText);
  } catch (error: any) {
    console.warn("This device is not supported.");
  }

**Expected behavior**

**Screenshots**

**React Native (please complete the following information):**
 - 0.74.1

**Device (please complete the following information):**
- V1S

**Additional context**
in the readme is supported to v1s, how to test it ?

**Comment by mitsuharu** [comment]
try `await SunmiPrinterLibrary.prepare()` with await.
 
OR

`Cannot read property 'connect'`  is that native code is missed. 
failed to add this library?

> 0.74.1

I have not checked 0.74 yet. If it causes by 0.74, I welcome your PR.

> V1S

I don't have a V1S so I haven't checked directly, but there are people using it with V1S.

**Comment by mitsuharu** [comment]
please run this Example app on your V1S

**Comment by saydfuad** [comment]
V2s  reply : connect fail

**Comment by mitsuharu** [comment]
This project is my hobby and I am busy right now, so I have no immediate plans to update it.

Please write bugs in detail, including your develop environment and how it happened, not just error result. 
Or please make a PR.

**Comment by mitsuharu** [comment]
I have integrated this library into other React Native 0.74 app, and it works at V2 Pro and V2s. I have updated the example to version 0.74, so please check it.
