### ISSUE TITLE
bug at printHR and setTextStyle function

### ISSUE THREAD

**Issue by suttapak** [mitsuharu/react-native-sunmi-printer-library#48]
**Describe the bug**
I have are bug vertion  "@mitsuharu/react-native-sunmi-printer-library": "^2.2.0",
1.  ERROR  printHR is failed.undefined
2. [Error: native#setTextStyle() is failed. this version does not support this method!]

**To Reproduce**
1. when use function printHR have error `printHR is failed.undefined`
```js
await SunmiPrinterLibrary.prepare();
await SunmiPrinterLibrary.printHR("double");
```
2. native#setTextStyle() `[Error: native#setTextStyle() is failed. this version does not support this method!]`
```js
await SunmiPrinterLibrary.setTextStyle("bold", true);
```
**Expected behavior**

**Screenshots**

**React Native (please complete the following information):**
 - Version: 0.74.5

**Device (please complete the following information):**
 - [MUST] Model:  SUNMI V2 PRO
 - [MUST] GMS: [I don't know about this]
 - Android vertion 7.1.2
 - SUNMI OS: [e.g. 3.6.23]
 - firmware: 65

**Additional context**

**Comment by suttapak** [comment]
my dependency
```json
"dependencies": {
    "@mitsuharu/react-native-sunmi-printer-library": "^2.2.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-navigation/native": "^6.1.18",
    "@rn-primitives/avatar": "~1.0.5",
    "@rn-primitives/label": "^1.0.4",
    "@rn-primitives/portal": "~1.0.4",
    "@rn-primitives/progress": "~1.0.4",
    "@rn-primitives/slot": "~1.0.4",
    "@rn-primitives/switch": "^1.0.4",
    "@rn-primitives/tooltip": "~1.0.4",
    "@rn-primitives/types": "~1.0.4",
    "@tanstack/react-query": "^5.56.2",
    "axios": "^1.7.7",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "dayjs": "^1.11.13",
    "expo": "^51.0.34",
    "expo-camera": "~15.0.16",
    "expo-haptics": "~13.0.1",
    "expo-linking": "~6.3.1",
    "expo-navigation-bar": "~3.0.7",
    "expo-router": "~3.5.23",
    "expo-splash-screen": "~0.27.6",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "immer": "^10.1.1",
    "lucide-react-native": "^0.445.0",
    "nativewind": "4.0.36",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-mmkv": "^2.6.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-web": "~0.19.12",
    "tailwind-merge": "^2.5.2",
    "tailwindcss": "3.4.13",
    "tailwindcss-animate": "^1.0.7",
    "zustand": "^4.5.5"
  },
```

**Comment by mitsuharu** [comment]
> 1. ERROR printHR is failed.undefined

I do not prepare this error message, so you may have failed to import it.

> 2. [Error: native#setTextStyle() is failed. this version does not support this method!]

setTextStyle calls native function setPrinterStyle. It needs certain versions or higher; "this version does not support this method". Please use another version of device or use ESC/POS command with sendRAWData.

![setPrinterStyle](https://github.com/user-attachments/assets/e8969cca-e5c6-4eb2-997e-8c2c34060006)

**Comment by suttapak** [comment]
Thank your for help :)
